sudo: false
language: node_js
node_js:
  - 8.1.1
test:
  - echo 'ok1'
before_script:
  - echo 'ok2'
script:
  - echo 'ok3'
before_deploy:
  - pip install --user awscli
  - ~/.local/bin/aws configure set preview.cloudfront true
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync web $BUCKET $REGION --delete
  skip_cleanup: true
  on:
    branch: master
