sudo: false
before_deploy:
  - pip install --user awscli
  - ~/.local/bin/aws configure set preview.cloudfront true
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync web $BUCKET $REGION --delete
  skip_cleanup: true
  on:
    branch: master
